version: '3.8'

services:
  frontend:
    image: rustamyusupov/rstm-frontend
    build:
      context: ./frontend
    ports:
      - '80:80'
    networks:
      - local
    depends_on:
      - backend

  backend:
    image: rustamyusupov/rstm-backend
    build:
      context: ./backend
    networks:
      - local

networks:
  local:
