version: '3.8'

services:
  frontend:
    image: registry.digitalocean.com/rstm-registry-container/frontend
    build:
      context: ./frontend
    ports:
      - '80:80'
    networks:
      - frontend
      - backend

  backend:
    image: registry.digitalocean.com/rstm-registry-container/backend
    build:
      context: ./backend
    networks:
      - backend

networks:
  frontend:
  backend:
