version: '3.8'

services:
  backend:
    image: rustamyusupov/rstm-backend
    restart: always
    volumes:
      - ./db.json:/usr/src/app/db.json
    expose:
      - 3000
    networks:
      - frontend-backend

  frontend:
    image: rustamyusupov/rstm-frontend
    restart: always
    ports:
      - '80:80'
      - '3000:3000'
    networks:
      - frontend-backend
    depends_on:
      - backend

networks:
  frontend-backend:
