version: '3.8'

services:
  backend:
    container_name: backend
    restart: always
    build: backend
    volumes:
      - ./db.json:/usr/src/app/db.json
    expose:
      - 3000
    networks:
      - frontend-backend

  frontend:
    container_name: frontend
    restart: always
    build: frontend
    ports:
      - '80:80'
      - '3000:3000'
    networks:
      - frontend-backend
    depends_on:
      - backend

networks:
  frontend-backend:
