version: '3.8'

services:
  backend:
    container_name: backend
    restart: always
    build: backend
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    expose:
      - 3000
    networks:
      - local

  frontend:
    container_name: frontend
    restart: always
    build: frontend
    volumes:
      - static:/usr/src/app
    networks:
      - local
    depends_on:
      - backend

  nginx:
    image: nginx:1.20.2-alpine
    ports:
      - '80:80'
      - '3000:3000'
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - static:/usr/share/nginx/html
    networks:
      - local
    depends_on:
      - frontend

volumes:
  static:

networks:
  local:
