version: '3.8'

services:
  app:
    image: rustamyusupov/rstm
    restart: always
    volumes:
      - ~/data/db.json:/usr/src/app/src/db.json
      - ~/data/users.json:/usr/src/app/src/users.json

  nginx:
    image: umputun/nginx-le:latest
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ~/maintain/ssl:/etc/nginx/ssl
      - ~/maintain/nginx.conf:/etc/nginx/service.conf
    environment:
      - TZ=GMT
      - LETSENCRYPT=true
      - LE_EMAIL=${EMAIL}
      - LE_FQDN=${FQDN}
    depends_on:
      - app
