version: '3.8'

services:
  backend:
    image: rustamyusupov/rstm-backend
    command: node dist/server.js
    networks:
      - local

  frontend:
    image: rustamyusupov/rstm-frontend
    volumes:
      - static:/dist
    networks:
      - local
    depends_on:
      - backend

  nginx:
    image: nginx:1.20.2-alpine
    ports:
      - '80:80'
      - '3000:3000'
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - static:/usr/share/nginx/html
    networks:
      - local
    depends_on:
      - frontend

  # nginx:
  #   image: umputun/nginx-le:latest
  #   hostname: nginx
  #   restart: always
  #   container_name: nginx
  #   ports:
  #     - '80:80'
  #     - '443:443'
  #     - '3000:3000'
  #   volumes:
  #     - ./default.conf:/etc/nginx/service.conf
  #     - static:/usr/share/nginx/html
  #   environment:
  #     - TZ=GMT
  #     - LETSENCRYPT=true
  #     - LE_EMAIL=${EMAIL}
  #     - LE_FQDN=${FQDN}
  #   networks:
  #     - local
  #   depends_on:
  #     - frontend
  #     - backend

volumes:
  static:

networks:
  local:
