version: '3.8'

services:
  db:
    image: postgres:14.2-alpine
    restart: always
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - ~/data:/var/lib/postgresql/data

  app:
    image: rustamyusupov/rstm
    restart: always
    environment:
      - SESSION_SECRET=${SESSION_SECRET}
    volumes:
      - ~/data/db.json:/usr/src/app/src/db.json
      - ~/data/users.json:/usr/src/app/src/users.json
    depends_on:
      - db

  nginx:
    image: umputun/nginx-le:latest
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ~/maintain/ssl:/etc/nginx/ssl
      - ~/maintain/nginx.conf:/etc/nginx/service.conf
    environment:
      - TZ=GMT
      - LETSENCRYPT=true
      - LE_EMAIL=${EMAIL}
      - LE_FQDN=${FQDN}
    depends_on:
      - app
