version: '3.8'

services:
  backend:
    image: rustamyusupov/rstm-backend
    command: node dist/server.js
    networks:
      - local

  frontend:
    image: rustamyusupov/rstm-frontend
    volumes:
      - static:/dist
    networks:
      - local
    depends_on:
      - backend

  nginx:
    image: umputun/nginx-le:latest
    hostname: nginx
    restart: always
    container_name: nginx
    ports:
      - '80:80'
      - '443:443'
      - '3000:3000'
    volumes:
      # - ./etc/ssl:/etc/nginx/ssl
      - ./default.conf:/etc/nginx/service.conf
      - static:/usr/share/nginx/html
    environment:
      - TZ=GMT
      - LETSENCRYPT=true
      - LE_EMAIL=i@rstm.me
      - LE_FQDN=rstm.me
    networks:
      - local
    depends_on:
      - frontend
      - backend

volumes:
  static:

networks:
  local:
