version: '3.8'

services:
  db:
    container_name: db
    image: postgres:14.2-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - ~/data:/var/lib/postgresql/data
      - ~/maintain/db.sql:/docker-entrypoint-initdb.d/db.sql
      - ~/data/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    container_name: app
    image: rustamyusupov/rstm
    restart: always
    environment:
      - SESSION_SECRET=${SESSION_SECRET}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    command: ./wait-for.sh db:${DB_PORT} -- node ./bin/www
    depends_on:
      - db

  nginx:
    container_name: nginx
    image: umputun/nginx-le:latest
    restart: always
    environment:
      - TZ=GMT
      - LETSENCRYPT=true
      - LE_EMAIL=${EMAIL}
      - LE_FQDN=${FQDN}
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ~/maintain/ssl:/etc/nginx/ssl
      - ~/maintain/nginx.conf:/etc/nginx/service.conf
    depends_on:
      - app
# volumes:
#   db:
#     driver: local
