version: '3.8'

services:
  app:
    image: rustamyusupov/rstm
    restart: always
    volumes:
      - ./db.json:/usr/src/app/db.json

  nginx:
    image: umputun/nginx-le:latest
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./etc/ssl:/etc/nginx/ssl
      - ./nginx.conf:/etc/nginx/service.conf
    environment:
      - TZ=GMT
      - LETSENCRYPT=true
      - LE_EMAIL=${EMAIL}
      - LE_FQDN=${FQDN}
    depends_on:
      - app
