version: '3.8'

services:
  app:
    image: rustamyusupov/rstm
    build:
      context: .
    restart: always
    volumes:
      - ./db.json:/usr/src/app/db.json
    networks:
      - app-nginx

  nginx:
    image: nginx:1.20.2-alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-nginx
    depends_on:
      - app

networks:
  app-nginx:
