name: Deploy

on:
  push:
    branches: [master]

env:
  REGISTRY: 'rustamyusupov'
  FRONTEND_IMAGE: 'rstm-frontend'
  BACKEND_IMAGE: 'rstm-backend'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Login to the Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build the Docker images
        run: docker-compose build --parallel
      - name: Push images to the Docker
        run: docker-compose push

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Copy files to DO
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          source: 'maintain/docker-compose.yml,maintain/default.conf'
          target: 'root'
      - name: Deploy on DO
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          envs: REGISTRY, FRONTEND_IMAGE, BACKEND_IMAGE, {{ secrets.DOCKERHUB_USERNAME }}, {{ secrets.DOCKERHUB_TOKEN }}
          script: |
            # Login to the Docker
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
            # Remove all containers
            docker rm -vf $(docker ps -aq)
            # Remove all images
            docker rmi -f $(docker images -aq)
            # Pull images
            docker pull $REGISTRY/$BACKEND_IMAGE:latest
            docker pull $REGISTRY/$FRONTEND_IMAGE:latest
            # Run containers
            docker-compose up -d
