name: deploy

on:
  push:
    branches:
      - 'master'

env:
  MAINTAIN: 'maintain'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 17
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: rustamyusupov/rstm:latest
      - uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          source: '${{ env.MAINTAIN }}/'
          target: '.'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          script: |
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
            docker-compose down
            docker rm -vf $(docker ps -aq)
            docker rmi -f $(docker images -aq)
            EMAIL=${{ secrets.EMAIL }} FQDN=${{ secrets.FQDN }} \
              DB_HOST=${{ secrets.DB_HOST }} DB_PORT=${{ secrets.DB_PORT }} \
              DB_DATABASE=${{ secrets.DB_DATABASE }} \
              DB_USERNAME=${{ secrets.DB_USERNAME }} DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
              SESSION_SECRET=${{ secrets.SESSION_SECRET }} \
              docker-compose -f ${{ env.MAINTAIN }}/docker-compose.yml up -d
