name: Deploy to DigitalOcean

on:
  push:
    branches: [master]

env:
  REGISTRY: 'rustamyusupov'
  IMAGE_NAME: 'rstm-frontend'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build the Docker image
        run: docker build -t $REGISTRY/$IMAGE_NAME:latest .
      - name: Docker Push
        run: docker push $REGISTRY/$IMAGE_NAME:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Digital Ocean droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          envs: IMAGE_NAME,REGISTRY,GITHUB_SHA,{{ secrets.DOCKERHUB_USERNAME }},{{ secrets.DOCKERHUB_TOKEN }}
          script: |
            # Login to registry
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
            # Stop running container
            docker stop $IMAGE_NAME
            # Remove old container
            docker rm $IMAGE_NAME
            # Pull container
            docker pull $REGISTRY/$IMAGE_NAME:latest
            # Run a new container from a new image
            docker run -d \
            --publish 80:80 \
            --restart always \
            --name $IMAGE_NAME \
            $REGISTRY/$IMAGE_NAME:latest
