name: Deploy to DigitalOcean

on:
  push:
    branches: [master]

env:
  REGISTRY: 'rustamyusupov'
  IMAGE_NAME: 'rstm-frontend'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build the Docker images
        run: docker-compose build
        # run: docker build -t $REGISTRY/$IMAGE_NAME:latest .
      - name: Docker Push
        run: docker-compose push
        # run: docker push $REGISTRY/$IMAGE_NAME:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Digital Ocean droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          envs: REGISTRY, IMAGE_NAME, {{ secrets.DOCKERHUB_USERNAME }}, {{ secrets.DOCKERHUB_TOKEN }}
          script: |
            # Login to registry
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
            # Delete all containers
            docker rm -vf $(docker ps -aq)
            # Remove all images
            docker rmi -f $(docker images -aq)
            # Pull container
            # docker pull $REGISTRY/$IMAGE_NAME:latest
            docker-compose pull
            # Run a new container from a new image
            docker-compose run -d
            # docker run -d \
            # --publish 80:80 \
            # --restart always \
            # --name $IMAGE_NAME \
            # $REGISTRY/$IMAGE_NAME:latest
